config/routes.rb
Rails.application.routes.draw do

  constraints(ClientDomainConstraint.new) do
    devise_for :users, controllers: {
      sessions: 'client/sessions',
      registrations: 'client/registrations'
    }
    scope module: :client, path: '' do
      root 'home#index'
      get 'users/invite', to: 'users#invite', format: :svg
      resources :profiles, only: [:show, :edit, :update]
      resources :addresses, except: :show
    end
  end

  constraints(AdminDomainConstraint.new) do
    namespace :admin, path: '' do
      root 'home#index'
      devise_for :users, controllers: {
        sessions: 'admin/sessions',
      }, as: :admin
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  enum genre: { home: 0, office: 1 }

  belongs_to :user

  belongs_to :region, class_name: 'Address::Region', foreign_key: 'address_region_id'
  belongs_to :province, class_name: 'Address::Province', foreign_key: 'address_province_id'
  belongs_to :city, class_name: 'Address::City', foreign_key: 'address_city_id'
  belongs_to :barangay, class_name: 'Address::Barangay', foreign_key: 'address_barangay_id'
end

app/models/address/barangay.rb
class Address::Barangay < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  belongs_to :city

  has_many :addresses, class_name: 'Address', foreign_key: 'address_barangay_id'

  def self.table_name_prefix
    "address_"
  end
end

app/models/address/city.rb
class Address::City < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  belongs_to :province
  has_many :barangays

  has_many :addresses, class_name: 'Address', foreign_key: 'address_city_id'

  def self.table_name_prefix
    "address_"
  end
end

app/models/address/province.rb
class Address::Province < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true

  belongs_to :region
  has_many :districts, class_name: 'Address::Province', foreign_key: :province_id
  has_many :cities
end

app/models/address/region.rb
class Address::Region < ApplicationRecord
  validates :name, presence: true
  validates :code, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: { client: 0, admin: 1 }

  validates :username, presence: true, uniqueness: true

  mount_uploader :image, ImageUploader
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < AdminController
  def index
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Devise::SessionsController
  layout 'admin'

  def create
    user = User.find_by(email: params[:admin_user][:email])
    if user&.admin?
      super
    else
      flash[:alert] = "Wrong email or password"
      redirect_to action: :new
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ActionController::Base
  layout 'admin'
end

app/controllers/api/v1/barangays_controller.rb
class Api::V1::BarangaysController < ApplicationController

  def index
    city = Address::City.find_by_id(params[:city_id])
    barangays = if city
                  city.barangays
                else
                  Address::Barangay.all
                end
    render json: barangays, each_serializer: Api::V1::BarangaysController
  end

  def show
    barangay = Address::Barangay.find(params[:id])
    render json: barangay, serializer: Api::V1::BarangaysController
  end
end

app/controllers/api/v1/cities_controller.rb
class Api::V1::CitiesController < ApplicationController

  def index
    province = Address::Province.find_by_id(params[:province_id])
    cities = if province
               province.cities
             else
               Address::City.all
             end

    render json: cities, each_serializer: Api::V1::CitiesController
  end

  def show
    city = Address::City.find(params[:id])
    render json: cities, each_serializer: Api::V1::CitiesController
  end
end

app/controllers/api/v1/provinces_controller.rb
class Api::V1::ProvincesController < ApplicationController

  def index
    region = Address::Region.find_by_id(params[:region_id])
    provinces = if region
                  region.provinces
                else
                  Address::Province.all
                end

    render json: provinces, each_serializer: Api::V1::ProvincesController
  end

  def show
    province = Address::Province.find_by_id(params[:id])
    render json: province, serializer: Api::V1::ProvincesController
  end
end

app/controllers/api/v1/regions_controller.rb
class Api::V1::RegionsController < ApplicationController

  def index
    regions = Address::Region.all
    render json: regions, each_serializer: Api::V1::RegionsController
  end

  def show
    region = Address::Region.find(params[:id])
    render json: region, serializer: Api::V1::RegionsController
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/client/home_controller.rb
class Client::HomeController < ApplicationController
  def index
  end
end

app/controllers/client/profiles_controller.rb
class Client::ProfilesController < ApplicationController
  before_action :authenticate_user!

  def show
  end

  def edit
    @client = current_user
  end

  def update
    @client = current_user

    if @client.update(client_params)
      redirect_to profile_path, notice: "Successfully Updated"
    else
      render :edit
    end
  end

  private

  def client_params
    params.require(:user).permit(:username, :email, :phone_number, :image)
  end
end

app/controllers/client/registrations_controller.rb
class Client::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]

  def new
    cookies[:promoter_email] ||= params[:promoter]
    super
  end

  def create
    super do |user|
      promoter_email = cookies[:promoter_email]
      if promoter_email && (promoter = User.find_by(email: promoter_email))
        user.update(parent_id: promoter.id)
      end
    end
  end

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up)
  end
end

app/controllers/client/sessions_controller.rb
class Client::SessionsController < Devise::SessionsController

  def create
    user = User.find_by(email: params[:user][:email])
    if user&.client?
      super
    else
      flash[:alert] = "Invalid email or password"
      redirect_to action: :new
    end
  end
end

app/controllers/client/users_controller.rb
class Client::UsersController < ApplicationController

  def invite
    if user_signed_in?
      @promoter_email = "client.com:3000/users/sign_up?promoter=#{current_user.email}"
    else
      @promoter_email = "http://client.com:3000/users/sign_in"
    end
    cookies[:promoter_email] = @promoter_email if @promoter_email
    qrcode = RQRCode::QRCode.new(@promoter_email)
    @qrcode_svg = qrcode.as_svg(module_size: 4)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = current_user
    @user.create_profile unless @user.profile
  end

  private

  def user_params
    params.require(:user).permit(:time_zone, profile_attributes: [:id, :legal_name, :birthday, :location, :education, :occupation, :bio, :specialty] )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/client/home/index.html.erb
<%= render partial: 'client/shared/banner' %>

<div class="container py-3"> <!-- Use a normal container for default spacing -->
  <h6 class="fw-bold">Announcement 🎉</h6>
  <p>We are thrilled to announce our latest casino promotions and offers that will make your gaming
    experience unforgettable! Join us this weekend for special bonuses, free spins, and chances to win big prizes. Don't
    miss out on the
    fun!</p>
</div>

<div class="bg-black py-3">
  <div class="container">
    <h6 class="fw-bold">Winner's Feedback</h6>
    <div class="row">
      <div class="col-md-3">
        <div class="card">
          <%= image_tag("winners/winner_1.png", class: "card-img-top", alt: "Card image cap", style: "height: 200px; object-fit: cover;") %>
          <div class="card-body">
            <h5 class="card-title">JackpotHunter</h5>
            <p class="card-text">"Hunting for jackpots finally paid off! Thanks to the casino's variety of games, I won a whopping $20,000. Unbelievable!"</p>
            <p class="card-text"><small class="text-muted">Earnings: $20,000</small></p>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card">
          <%= image_tag("winners/winner_2.png", class: "card-img-top", alt: "Card image cap", style: "height: 200px; object-fit: cover;") %>
          <div class="card-body">
            <h5 class="card-title">CasinoQueen</h5>
            <p class="card-text">"Feeling like a casino queen today! The $8,500 I won has exceeded my expectations. Can't wait to play again!"</p>
            <p class="card-text"><small class="text-muted">Earnings: $8,500</small></p>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card">
          <%= image_tag("winners/winner_3.png", class: "card-img-top", alt: "Card image cap", style: "height: 200px; object-fit: cover;") %>
          <div class="card-body">
            <h5 class="card-title">LuckyGambler</h5>
            <p class="card-text">"I can't believe my luck! Winning $5,000 at the casino has made my day. Thank you for the amazing experience."</p>
            <p class="card-text"><small class="text-muted">Earnings: $5,000</small></p>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card">
          <%= image_tag("winners/winner_4.png", class: "card-img-top", alt: "Card image cap", style: "height: 200px; object-fit: cover;") %>
          <div class="card-body">
            <h5 class="card-title">HighRoller88</h5>
            <p class="card-text">"Being a high roller paid off big time! I walked away with $10,000 in winnings. I'm having so much fun. This casino is my new favorite."</p>
            <p class="card-text"><small class="text-muted">Earnings: $10,000</small></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="bg-black py-3">
  <div class="container">
    <h6 class="fw-bold text-white">Coming Soon</h6>
    <div class="row">
      <div class="col-md-3">
        <div class="card">
          <a href="#">
            <%= image_tag("games/game1.png", class: "card-img-top", alt: "Game 1", style: "height: 200px; object-fit: cover;") %>
          </a>
          <div class="card-body">
            <h5 class="card-title">
              <a href="#" style="text-decoration: none; color: inherit;">Mystic Quest</a>
            </h5>
            <p class="card-text">Embark on an epic adventure in our new mystical-themed slot game. Uncover hidden treasures and unlock magical bonuses! <a href="#" class="link-danger link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Play here!</a></p>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card">
          <a href="#">
            <%= image_tag("games/game2.png", class: "card-img-top", alt: "Game 2", style: "height: 200px; object-fit: cover;") %>
          </a>
          <div class="card-body">
            <h5 class="card-title">
              <a href="#" style="text-decoration: none; color: inherit;">Roulette Royale</a>
            </h5>
            <p class="card-text">Get ready to spin the wheel in style with our new Roulette Royale game. Bet big and win bigger in this exciting variation of roulette! <a href="#" class="link-danger link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Play here!</a></p>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card">
          <a href="#">
            <%= image_tag("games/game3.png", class: "card-img-top", alt: "Game 3", style: "height: 200px; object-fit: cover;") %>
          </a>
          <div class="card-body">
            <h5 class="card-title">
              <a href="#" style="text-decoration: none; color: inherit;">Sports Betting</a>
            </h5>
            <p class="card-text">Get in on the action with our upcoming sports betting feature. Bet on your favorite teams and enjoy live updates and odds! <a href="#" class="link-danger link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover"> Play here!</a></p>
          </div>
        </div>
      </div>
      <div class="col-md-3">
        <div class="card">
          <a href="#">
            <%= image_tag("games/game4.png", class: "card-img-top", alt: "Game 4", style: "height: 200px; object-fit: cover;") %>
          </a>
          <div class="card-body">
            <h5 class="card-title">
              <a href="#" style="text-decoration: none; color: inherit;">Blackjack Blitz</a>
            </h5>
            <p class="card-text">Prepare for fast-paced blackjack action in our upcoming Blackjack Blitz game. Race against the clock and challenge other players! <a href="#" class="link-danger link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">Play here!</a></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/client/profiles/edit.html.erb
<style>
    .gradient-custom {
        /* fallback for old browsers */
        background: #6a11cb;

        /* Chrome 10-25, Safari 5.1-6 */
        background: -webkit-linear-gradient(to right, rgba(106, 17, 203, 1), rgba(37, 117, 252, 1));

        /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        background: linear-gradient(to right, rgba(106, 17, 203, 1), rgba(37, 117, 252, 1))
    }
</style>
<section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-black text-white" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

            <div class="mb-md-5 mt-md-4">
              <h2 class="fw-bold mb-2 text-uppercase">Edit My Profile</h2>
              <p class="text-white-50 mb-5">Update your profile information</p>
            </div>

            <%= form_with(model: current_user, url: profile_path, method: :patch) do |form| %>
              <div class="form-group mb-3">
                <%= form.label :username, class: "form-label text-white" %>
                <%= form.text_field :username, class: "form-control", placeholder: "Username" %>
              </div>

              <div class="form-group mb-3">
                <%= form.label :phone_number, class: "form-label text-white" %>
                <%= form.text_field :phone_number, class: "form-control", placeholder: "Phone Number" %>
              </div>

              <div class="form-group mb-3">
                <%= form.label :image, class: "form-label text-white" %>
                <%= form.file_field :image, class: "form-control" %>
              </div>

              <div class="actions">
                <%= form.submit "Update", class: "btn btn-outline-light btn-lg px-5 mb-5" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/client/profiles/show.html.erb
<div class="container py-3 px-md-5"> <!-- Increase padding on larger screens -->
  <div class="card-body text-start d-flex flex-wrap align-items-center justify-content-between">
    <div class="d-flex align-items-center">
      <div class="ms-3">
        <p class="nav-link active" aria-current="page">
          Username: <%= current_user ? current_user.username : '' %>
        </p>
        <p class="nav-link active" aria-current="page">
          Email: <%= current_user ? current_user.email : '' %>
        </p>
        <p class="nav-link active" aria-current="page">
          Coins: <%= current_user ? current_user.coins : '' %>
        </p>
      </div>
    </div>

    <div class="w-100 m-3">
      <div class="d-flex justify-content-center">
        <%= link_to "Cash In Now", "#", class: "btn btn-primary w-100" %>
      </div>
      <div class="d-flex justify-content-center gap-1 mt-2">
        <%= link_to "Edit Profile", edit_profile_path, class: "btn btn-primary w-50" %>
        <a href="#" class="btn btn-primary w-50">Address</a>
      </div>
    </div>
  </div>
</div>

app/views/client/shared/_footer.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-black p-3">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Toggle button -->
    <button
      class="navbar-toggler ms-auto"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarCenteredExample"
      aria-controls="navbarCenteredExample"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Collapsible wrapper -->
    <div
      class="collapse navbar-collapse justify-content-center"
      id="navbarCenteredExample"
    >
      <!-- Left links -->
      <ul class="navbar-nav mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Share', '#', class: 'nav-link mx-2', 'aria-current': 'page' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Invite', users_invite_path, class: 'nav-link mx-2' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Lottery', '#', class: 'nav-link mx-2' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Shop', '#', class: 'nav-link mx-2' %>
        </li>
        <% if current_user %>
          <li class="nav-item">
            <%= link_to 'Me', profile_path(current_user), class: 'nav-link mx-2' %>
          </li>
        <% end %>
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>

app/views/client/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-black p-3 sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link mx-2 active" aria-current="page" href="#">Coins</a>
        </li>
        <li class="nav-item">
          <a class="nav-link mx-2" href="#">Claim</a>
        </li>
        <li class="nav-item">
          <a class="nav-link mx-2" href="#">Language</a>
        </li>
        <li class="nav-item">
          <!-- Offcanvas toggler button -->
          <% if current_user %>
            <button class="btn btn-outline-dark" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon" data-bs-target="#offcanvasDarkNavbar"></span>
            </button>
          <% else %>
            <a><%= link_to 'Sign in', new_user_session_path, class: "nav-link mx-2" %></a>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<!-- Offcanvas content -->
<div class="offcanvas offcanvas-end text-bg-dark bg-black" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">MENU</h5>
    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
      <li class="nav-item">
        Username: <%= current_user&.username %>
      </li>
      <li class="nav-item">
        Email: <%= current_user&.email %>
      </li>
      <li class="nav-item">
        Coins: <%= current_user&.coins %>
      </li>
    </ul>
    <button style="width:100%" type="button" class="btn btn-primary btn-lg">Cash In Now</button>
    <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
      <li><a class="dropdown-item" href="#">Contact Us</a></li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "My Profile", profile_path(current_user), class: "dropdown-item" %>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to 'Sign out', destroy_user_session_path, class: "dropdown-item", data: { 'turbo-method': :delete } %>
      </li>
    </ul>
  </div>
</div>

app/views/client/shop/index.html.erb
<h2>Shop Page</h2>

app/views/client/users/invite.html.erb
<style>
    .gradient-custom {
        /* fallback for old browsers */
        background: #6a11cb;

        /* Chrome 10-25, Safari 5.1-6 */
        background: -webkit-linear-gradient(to right, rgba(106, 17, 203, 1), rgba(37, 117, 252, 1));

        /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        background: linear-gradient(to right, rgba(106, 17, 203, 1), rgba(37, 117, 252, 1))
    }
</style>
<section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-black text-white" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

            <div class="mb-md-3 mt-md-4 py-2">
              <h1 class="fw-bold mb-2 text-uppercase">Invite</h1>
              <p class="text-white opacity-75">Share this QR code and invite people to have some casino fun!</p>
            </div>

            <div class="bg-white d-flex justify-content-center align-items-center rounded p-4 ms-auto me-auto p-4" style="width: 200px; height: 200px;">
              <%= raw @qrcode_svg %>
            </div>

            <p class="text-white" style="margin-right: 10px; margin-top: 10px;">Invite URL: <a href="<%= new_user_session_path(promoter: @promoter_email) %>" class="link-light link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover"><%= @promoter_email %></a></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>